python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample TT01j2lCAv2Ref_HT500 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample TTLep_pow_CP5_hUp 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample TTLep_pow_CP5_hDown 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample TTLep      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample ST      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample TTW     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample TTZ     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample TTH     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample DY      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT --sample DiBoson 

python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample TT01j2lCAv2Ref_HT500 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample TTLep_pow_CP5_hUp 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample TTLep_pow_CP5_hDown 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample TTLep      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample ST      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample TTW     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample TTZ     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample TTH     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample DY      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16_preVFP --sample DiBoson 

python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample TT01j2lCAv2Ref_HT500 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample TTLep_pow_CP5_hUp 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample TTLep_pow_CP5_hDown 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample TTLep      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample ST      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample TTW     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample TTZ     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample TTH     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample DY      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Summer16        --sample DiBoson 

python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample TT01j2lCAv2Ref_HT500 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample TTLep_pow_CP5_hUp 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample TTLep_pow_CP5_hDown 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample TTLep      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample ST      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample TTW     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample TTZ     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample TTH     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample DY      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Fall17         --sample DiBoson 

python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample TT01j2lCAv2Ref_HT500 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample TTLep_pow_CP5_hUp 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample TTLep_pow_CP5_hDown 
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample TTLep      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample ST      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample TTW     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample TTZ     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample TTH     
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample DY      
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v4 --config EFT_Autumn18       --sample DiBoson 
