python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_nominal
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalPileUpUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalRelativeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalAbsoluteUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalPtUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalScaleUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalMCUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalNoFlavorUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalNoFlavorNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTimePtEtaUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalPileUpDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalRelativeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalAbsoluteDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalPtDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalScaleDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesSubTotalMCDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalNoFlavorDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTotalNoFlavorNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_0p5_jesTimePtEtaDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalPileUpUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalRelativeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalAbsoluteUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalPtUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalScaleUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalMCUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalNoFlavorUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalNoFlavorNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTimePtEtaUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalPileUpDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalRelativeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalAbsoluteDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalPtDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalScaleDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesSubTotalMCDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalNoFlavorDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTotalNoFlavorNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p0_jesTimePtEtaDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalPileUpUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalRelativeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalAbsoluteUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalPtUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalScaleUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalMCUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalNoFlavorUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalNoFlavorNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTimePtEtaUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalPileUpDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalRelativeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalAbsoluteDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalPtDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalScaleDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesSubTotalMCDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalNoFlavorDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTotalNoFlavorNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_1p5_jesTimePtEtaDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalPileUpUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalRelativeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalAbsoluteUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalPtUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalScaleUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalMCUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalNoFlavorUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalNoFlavorNoTimeUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTimePtEtaUp
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalPileUpDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalRelativeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalAbsoluteDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalPtDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalScaleDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesSubTotalMCDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalNoFlavorDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTotalNoFlavorNoTimeDown
python make_ntuple.py --output /eos/vbc/group/cms/robert.schoefbeck/TT2lUnbinned/training-ntuples-v7-jec --config JEC_for_paper --sample  TTLep_2p0_jesTimePtEtaDown

